dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.8.5"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis_zones.yaml zones.yaml
install:
  - pip3 install homeassistant
  - git clone https://github.com/custom-components/ble_monitor.git ble_monitor/
  - mv ble_monitor/custom_components custom_components
  - git clone https://github.com/camect/home-assistant-integration.git camect/
  - mv camect custom_components
  - git clone https://github.com/custom-components/circadian_lighting.git circadian_lighting/
  - mv circadian_lighting/custom_components custom_components
  - git clone https://github.com/bmccluskey/robovac.git robovac/
  - mv robovac/custom_components/robovac custom_components
  - git clone https://github.com/custom-components/eventsensor.git eventsensor/
  - mv eventsensor/custom_components custom_components
  - git clone https://github.com/custom-components/garbage_collection.git garbage_collection/
  - mv garbage_collection/custom_components custom_components
  - git clone https://github.com/custom-components/google_home.git google_home/
  - mv google_home/custom_components custom_components
  - git clone https://github.com/hacs/integration.git hacs/
  - mv hacs/custom_components custom_components
  - git clone https://github.com/custom-components/unifigateway.git unifigateway/
  - mv unifigateway/custom_components custom_components
  - git clone https://github.com/sebr/bhyve-home-assistant.git bhyve-home-assistant/
  - mv bhyve-home-assistant/custom_components/bhyve custom_components
script:
  - hass -c . --script check_config
